language: java
before_script:
 - "echo $JAVA_OPTS"
 - "export JAVA_OPTS=-Xmx512m"
script:
- "mvn -Pidm-smoke-tests -Dtest.idm.store=jpa clean install" 
jdk:
- openjdk7
branches:
  only:
  - master
notifications:
  irc: irc.freenode.org#picketlink
